//
//  HomeConfigurator.swift
//  SleepTimer
//
//  Created by Petrov Anton on 15.06.2020.
//  Copyright © 2020 APM. All rights reserved.
//
//  This file was generated by the MVVM Core Xcode template
//

import UIKit

struct HomeConfigurator {
  
  private init () { }
  
  static func `default`(router: HomeRouterProtocol) -> HomeViewController {
    let viewController = HomeViewController()
    return configure(router: router, viewController: viewController)
  }
  
  static func fromStoryboard(router: HomeRouterProtocol) -> HomeViewController {
    let viewController = HomeViewController.instantiateFromStoryboard(storyboard: .home)
    return configure(router: router, viewController: viewController)
  }
  
  // MARK: Private
  
  private static func configure(router: HomeRouterProtocol, viewController: HomeViewController) -> HomeViewController {
    let playerUseCase = PlayerUseCase()
    let recorderUseCase = RecorderUseCase()
    let viewModel = HomeViewModel(router: router,
                                  playerUseCase: playerUseCase,
                                  recorderUseCase: recorderUseCase)
    viewController.viewModel = viewModel
    return viewController
  }
  
}

// MARK: - Mocking init

private extension PlayerUseCase {
  init(isMocking: Bool = STProcessInfo.isMocking) {
    repository = isMocking ? PlayerMockRepository(): PlayerRepository()
  }
}

private extension RecorderUseCase {
  init(isMocking: Bool = STProcessInfo.isMocking) {
    repository = isMocking ? RecorderMockRepository(): RecorderRepository()
  }
}
