//
//  HomeConfigurator.swift
//  SleepTimer
//
//  Created by Petrov Anton on 15.06.2020.
//  Copyright © 2020 APM. All rights reserved.
//
//  This file was generated by the MVVM Core Xcode template
//

import UIKit

struct HomeConfigurator {
  
  private init () { }
  
  static func `default`(router: HomeRouterProtocol) -> HomeViewController {
    let viewController = HomeViewController()
    return configure(router: router, viewController: viewController)
  }
  
  static func fromStoryboard(router: HomeRouterProtocol) -> HomeViewController {
    let viewController = HomeViewController.instantiateFromStoryboard(storyboard: .home)
    return configure(router: router, viewController: viewController)
  }
  
  // MARK: Private
  
  private static func configure(router: HomeRouterProtocol, viewController: HomeViewController) -> HomeViewController {
    let viewModel = HomeViewModel(router: router)
    viewController.viewModel = viewModel
    return viewController
  }
  
}
