//
//  HomeRouter.swift
//  SleepTimer
//
//  Created by Petrov Anton on 15.06.2020.
//  Copyright © 2020 APM. All rights reserved.
//
//  This file was generated by the MVVM Core Xcode template
//

import UIKit

protocol HomeRouterProtocol: RouterProtocol {
  func present<T: PrettyEnumValue>(message: String, value: Observable<T>, ranges: [T])
}

class HomeRouter: HomeRouterProtocol {

  weak var baseViewController: UIViewController?
  
  func present<T: PrettyEnumValue>(message: String, value: Observable<T>, ranges: [T]) {
    guard let baseViewController = baseViewController else { return }
    let alertController = UIAlertController(title: nil, message: message, preferredStyle: .actionSheet)
    ranges.forEach { range in
      let action = UIAlertAction(title: range.prettyValue, style: .default) { _ in
        value.value = range
        alertController.dismiss(animated: true)
      }
      alertController.addAction(action)
    }
    
    let cancelAction = UIAlertAction(title: "Cancel", style: .cancel) { _ in
      alertController.dismiss(animated: true)
    }
    alertController.addAction(cancelAction)
    
    baseViewController.present(alertController, animated: true)
  }
  
}
