//
//  HomeViewController.swift
//  SleepTimer
//
//  Created by Petrov Anton on 15.06.2020.
//  Copyright © 2020 APM. All rights reserved.
//
//  This file was generated by the MVVM Core Xcode template
//

import UIKit

final class HomeViewController: UIViewController {
  
  var viewModel: HomeViewModelProtocol!
  
  // MARK: - Outlets
  
  @IBOutlet var appStateLabel: UILabel!
  @IBOutlet var homeButton: UIButton!
  @IBOutlet var optionsTableView: UITableView!
  
  override func viewDidLoad() {
    super.viewDidLoad()
    setupUI()
    bind(viewModel)
  }
}

// MARK: - Actions

private typealias Actions = HomeViewController
private extension Actions {
  @objc func didSelectHomeButton() {
    viewModel.didSelectHomeButton()
  }
}

// MARK: - DataBinding

private typealias DataBinding = HomeViewController
private extension DataBinding {
  func bind(_ viewModel: HomeViewModelProtocol) {
    viewModel.appStateTitle.observeWithStartingValue(on: self) { [weak self] value in
      self?.appStateLabel.text = value
    }
    
    viewModel.homeButtonTitle.observeWithStartingValue(on: self) { [weak self] value in
      self?.homeButton.setTitle(value, for: .normal)
    }
    
    viewModel.reloadRows.observeWithStartingValue(on: self) { [weak self] in
      self?.optionsTableView.reloadData()
    }
  }
}

// MARK: - Private

private typealias UISetups = HomeViewController
private extension UISetups {
  func setupUI() {
    homeButton.addTarget(self, action: #selector(didSelectHomeButton), for: .touchUpInside)
    setupTableView()
  }
  
  func setupTableView() {
    
  }
}
