//
//  HomeViewModel.swift
//  SleepTimer
//
//  Created by Petrov Anton on 15.06.2020.
//  Copyright © 2020 APM. All rights reserved.
//
//  This file was generated by the MVVM Core Xcode template
//

import Foundation

protocol HomeViewModelInput {
  func didSelectHomeButton()
}

protocol HomeViewModelOutput {
  var isEnableOptions: Observable<Bool> { get }
  var appStateTitle: Observable<String> { get }
  var homeButtonTitle: Observable<String> { get }
  var reloadRows: ObservableEmpty { get }
  var rows: [HomeRows] { get }
}

protocol HomeViewModelProtocol: HomeViewModelInput, HomeViewModelOutput  { }

final class HomeViewModel: HomeViewModelProtocol {
  
  fileprivate let router: HomeRouterProtocol
  private let playerUseCase: PlayerUseCaseProtocol
  private let recorderUseCase: RecorderUseCaseProtocol
  
  init(router: HomeRouterProtocol,
       playerUseCase: PlayerUseCaseProtocol,
       recorderUseCase: RecorderUseCaseProtocol) {
    self.router = router
    self.playerUseCase = playerUseCase
    self.recorderUseCase = recorderUseCase
    soundTimerOption.observe(on: self, observerBlock: { _ in self.reloadRows.notify() })
    recordingDurationOption.observe(on: self, observerBlock: { _ in self.reloadRows.notify() })
    playerUseCase.observeSoundDidEndPlaying { self.appState = .idle }
  }
  
  private var appState = HomeAppState.idle {
    didSet {
      setupUIStatus(by: appState)
    }
  }
  
  private var homeButtonState = HomeButtomState.play
  
  fileprivate let soundTimerOption = Observable(SoundTimerOption.default)
  fileprivate var recordingDurationOption = Observable(RecordingDurationOption.default)
  
  // MARK: MoviesListViewModelOutput
  
  var reloadRows = ObservableEmpty()
  
  var isEnableOptions = Observable(true)
  
  var rows: [HomeRows] {
    let soundTimerRow = HomeRows.soundTimer(value: soundTimerOption.value.prettyValue,
                                            didSelect: self.openSoundTimerOptions)
    let recordingDurationRow = HomeRows.recordingDuration(value: recordingDurationOption.value.prettyValue,
                                                          didSelect: self.openRecordingDurationOptions)
    return [soundTimerRow, recordingDurationRow]
  }
  
  lazy var appStateTitle: Observable<String> = {
    return Observable(HomeAppState.idle.prettyValue)
  }()
  
  lazy var homeButtonTitle: Observable<String> = {
    Observable(HomeButtomState.play.prettyValue)
  }()
  
  // MARK: MoviesListViewModelInput
  
  func didSelectHomeButton() {
    switch (appState, homeButtonState) {
    case (.idle, .play), (.paused, .play):
      self.appState = .playing
      playerUseCase.playSound(soundTimer: soundTimerOption.value)
    case (.playing, .pause):
      self.appState = .paused
      playerUseCase.pauseSound()
    case (.recording, .pause): ()
      // in progress
    case (.recording, .play): ()
      // in progress
    default: ()
    }
  }
}

// MARK: - Private

private typealias Private = HomeViewModel
private extension Private {
  
  func openSoundTimerOptions() {
    router.present(message: "Sound Timer", value: soundTimerOption, ranges: SoundTimerOption.defaultRange)
  }
  
  func openRecordingDurationOptions() {
    router.present(message: "Recording Duration", value: recordingDurationOption, ranges: RecordingDurationOption.defaultRange)
  }
  
  func setupUIStatus(by status: HomeAppState) {
    appStateTitle.value = status.prettyValue
    switch status {
    case .idle:
      self.homeButtonState = .play
      self.isEnableOptions.value = true
    case .paused:
      homeButtonState = .play
      isEnableOptions.value = false
    case .playing:
      homeButtonState = .pause
      isEnableOptions.value = false
    case .recording:
      homeButtonState = .pause
      isEnableOptions.value = false
    }
    homeButtonTitle.value = homeButtonState.prettyValue
  }
  
}
